name: cupcake-technicaldata
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.7
  - aiosignal=1.3.2
  - appdirs=1.4.4
  - async-timeout=5.0.1
  - attrs=25.3.0
  - beautifulsoup4=4.13.4
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - curl-cffi=0.11.1
  - frozendict=2.4.6
  - frozenlist=1.6.0
  - h2=4.2.0
  - hpack=4.1.0
  - html5lib=1.1
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.10
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - liblapack=3.9.0
  - libopenblas=0.3.29
  - libsqlite=3.46.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libta-lib=0.4.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.2.13
  - lxml=5.2.2
  - multidict=6.4.4
  - multitasking=0.0.9
  - ncurses=6.4
  - numpy=2.2.6
  - openssl=3.5.0
  - pandas=2.2.3
  - peewee=3.17.6
  - pip=25.1
  - platformdirs=4.3.8
  - propcache=0.3.1
  - protobuf=5.28.3
  - pthread-stubs=0.3
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=78.1.1
  - six=1.17.0
  - soupsieve=2.7
  - sqlite=3.45.3
  - ta-lib=0.5.1
  - tk=8.6.14
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - urllib3=2.4.0
  - webencodings=0.5.1
  - websockets=15.0.1
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yarl=1.20.0
  - yfinance=0.2.61
  - zlib=1.2.13
  - zstandard=0.23.0
prefix: /home/abhishek/anaconda3/envs/cupcake-technicaldata
